AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
    
  ProvisionedFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.provisioned
      Runtime: nodejs12.x
      CodeUri: ./provisioned
      AutoPublishAlias: live
      Timeout: 10
      Tracing: Active
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 50
      Events:
        HelloAPI:
          Type: HttpApi
          Properties:
            Path: /provisioned
            Method: GET
    
  OndemandFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.ondemand
      Runtime: nodejs12.x
      CodeUri: ./ondemand
      Timeout: 10
      Tracing: Active
      Events:
        HelloAPI:
          Type: HttpApi
          Properties:
            Path: /ondemand
            Method: GET
  
Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region