AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
    
  ProvisionedFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.provisioned
      Runtime: nodejs12.x
      CodeUri: ./provisioned
      AutoPublishAlias: live
      Timeout: 120
      Tracing: Active
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 10
      Events:
        HelloAPI:
          Type: HttpApi
          Properties:
            Path: /provisioned
            Method: GET
            ApiId: !Ref MyApi
    
  OndemandFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.ondemand
      Runtime: nodejs12.x
      CodeUri: ./ondemand
      Timeout: 120
      Tracing: Active
      Events:
        HelloAPI:
          Type: HttpApi
          Properties:
            Path: /ondemand
            Method: GET
            ApiId: !Ref MyApi
  
Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region
    
  ApiId:
    Description: "API ID"
    Value: !Ref MyApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/'